[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DSA-scripts"
version = "0.1.0"
description = "A package for Manim scripts, nodes, arrows, etc."
dependencies = []
